import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import Booking from './booking/Booking';
import Confirmation from './confirmation/Confirmation';

/**
 * Helper to render the component with necessary router context and future flags.
 * We include both Booking and Confirmation to test the full navigation flow.
 */
const renderWithRouter = () => {
    return render(
        <MemoryRouter 
            initialEntries={['/']}
            future={{ v7_startTransition: true, v7_relativeSplatPath: true }}
        >
            <Routes>
                <Route path="/" element={<Booking />} />
                <Route path="/confirmation" element={<Confirmation />} />
            </Routes>
        </MemoryRouter>
    );
};

describe('Booking View', () => {
  
    it('should allow the user to fill in date and time', () => {
        // ARRANGE
        renderWithRouter();

        // ACT
        const dateInput = screen.getByLabelText(/Date/i) as HTMLInputElement;
        const timeInput = screen.getByLabelText(/Time/i) as HTMLInputElement;

        fireEvent.change(dateInput, { target: { value: '2026-05-20', name: 'when' } });
        fireEvent.change(timeInput, { target: { value: '18:00', name: 'time' } });

        // ASSERT
        expect(dateInput.value).toBe('2026-05-20');
        expect(timeInput.value).toBe('18:00');
    });

    it('should show an error message if fields are missing', async () => {
        // ARRANGE
        renderWithRouter();

        // ACT - Click strike immediately without filling anything
        const bookButton = screen.getByRole('button', { name: /str.*ike/i });
        fireEvent.click(bookButton);

        // ASSERT - Matching the string from your Booking.tsx
        const errorMessage = await screen.findByText(/All fields must be filled in./i);
        expect(errorMessage).toBeInTheDocument();
    });

    it('should complete a full booking flow and navigate to confirmation', async () => {
        // ARRANGE
        renderWithRouter();

        // ACT - Fill in all details
        // Note: Using 'name' in target to match your updateBookingDetails logic
        fireEvent.change(screen.getByLabelText(/Date/i), { target: { value: '2026-12-24', name: 'when' } });
        fireEvent.change(screen.getByLabelText(/Time/i), { target: { value: '18:00', name: 'time' } });
        fireEvent.change(screen.getByLabelText(/Number of awesome bowlers/i), { target: { value: '1', name: 'people' } });
        fireEvent.change(screen.getByLabelText(/Number of lanes/i), { target: { value: '1', name: 'lanes' } });

        // Add a shoe (matches people count)
        const addShoeButton = screen.getByText('+');
        fireEvent.click(addShoeButton);

        // Fill in shoe size (using the ID/name generated by your component)
        const shoeInput = screen.getByLabelText(/Shoe size \/ person 1/i);
        fireEvent.change(shoeInput, { target: { value: '42', name: shoeInput.getAttribute('name') } });

        // Submit
        const bookButton = screen.getByRole('button', { name: /str.*ike/i });
        fireEvent.click(bookButton);

        // ASSERT - Verify navigation to Confirmation
        // This confirms the API call was successful (via MSW) and navigate() was called
        const confirmationHeading = await screen.findByText(/See you soon!/i);
        expect(confirmationHeading).toBeInTheDocument();
    });
});
